version: "3.8"
services:
  tomcat:
    image: tomcat:8.5.75-jdk17
    container_name: tomcat-web
    hostname: tomcat-web
    ports:
      - 8080:8080
    volumes:
      - ./BackEnd:/usr/local/tomcat/webapps
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 7hHeKT5jJxVGsU
    links:
      - database:database
  database:
    image: mysql:8.0.29
    container_name: mysql
    hostname: mysql
    ports:
      - 65514:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 7hHeKT5jJxVGsU
    restart: unless-stopped
  nginx:
    image: nginx:stable
    container_name: nginx-web
    hostname: nginx-web
    ports:
      - 80:80
    volumes:
      - ./FrontEnd:/usr/share/nginx/html/
    links:
      - tomcat:tomcat
