version: "3.8"
services:
  node:
    image: node:18
    container_name: node-web
    hostname: node-web
    ports:
      - 3000:3000
    volumes:
      - ./BackEnd:/BackEnd
    working_dir: /BackEnd
    command: npm run start
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 7hHeKT5jJxVGsU
    links:
      - database:database
  database:
    image: mysql:8.0.29
    container_name: mysql
    hostname: mysql
    ports:
      - 65514:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 7hHeKT5jJxVGsU
    restart: unless-stopped
  nginx:
    image: nginx:stable
    container_name: nginx-web
    hostname: nginx-web
    ports:
      - 80:80
    volumes:
      - ./FrontEnd:/usr/share/nginx/html/
    links:
      - node:node
